"use strict";
const $=id=>document.getElementById(id);
let meta,players=[],weightMap={},requestSerial=0;
const labels={nonpenalty_xg:"Non-penalty xG",shot_linked_xg_assisted:"Shot-linked xG assisted",pass_completion_pct:"Pass completion %",carry_displacement:"Carry displacement",xg:"xG"};
const label=k=>labels[k]||k.replaceAll("_"," ").replace(/^./,c=>c.toUpperCase());
const number=v=>v==null?"Unavailable":Number(v).toLocaleString(undefined,{maximumFractionDigits:2});
const statuses={INSUFFICIENT_PEERS:"Not enough complete players for this comparison.",INELIGIBLE_QUERY:"This player's minutes, season coverage, or positional usage do not meet peer eligibility.",MISSING_QUERY_FEATURES:"Required query metrics are incomplete.",NO_VARIABLE_FEATURES:"The complete peer population has no variable metrics to compare.",CONSTANT_COMPONENT:"A required metric is constant in the peer population. No weights were redistributed.",NO_CANDIDATES:"No candidates meet the requested filters.",INELIGIBLE_PROFILE:"Player is outside the eligible peer population.",MISSING_METRIC:"Metric incomplete",MISSING_COMPONENT:"Required component incomplete",CONSTANT_METRIC:"No variation in peers",UNSUPPORTED_DATA:"Not supported by available data",DESCRIPTIVE_ONLY:"Descriptive value; no percentile"};
function node(tag,text,cls){const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;}
function clear(id){$(id).replaceChildren();return $(id);}
function message(parent,text,cls="message"){parent.append(node("p",text,cls));}
function ref(value){const [player_id,team_id]=value.split("|");return {player_id,team_id};}
function key(p){return p.player_id+"|"+p.team_id;}
function selectFill(id,rows,optional=false){const s=$(id),old=s.value;s.replaceChildren();if(optional)s.append(new Option("No third player",""));for(const p of rows)s.append(new Option(`${p.player_name} · ${p.team_name} (${p.primary_position_group||"mixed"})`,key(p)));if([...s.options].some(o=>o.value===old))s.value=old;}
async function api(path,body){const response=await fetch(path,body?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:{});const value=await response.json();if(!response.ok){const d=value.detail;throw Error(typeof d==="string"?d:Array.isArray(d)?d.map(e=>e.msg).join("; "):"Request failed");}return value;}
function query(params){return new URLSearchParams(params).toString();}
async function action(button,output,work){button.disabled=true;const parent=clear(output);message(parent,"Calculating from the verified snapshot…");try{await work(parent);}catch(e){parent.replaceChildren();message(parent,e.message,"message error");}finally{button.disabled=false;}}
function table(headers,rows){const wrap=node("div",null,"scroll"),t=node("table"),head=node("thead"),hr=node("tr");for(const h of headers)hr.append(node("th",h));head.append(hr);t.append(head);const body=node("tbody");for(const row of rows){const tr=node("tr");for(const value of row){const td=node("td");td.append(value instanceof Node?value:document.createTextNode(String(value)));tr.append(td);}body.append(tr);}t.append(body);wrap.append(t);return wrap;}
function card(title){const c=node("div",null,"card");if(title)c.append(node("h3",title));return c;}
function percentile(v){const d=node("div",null,"metric-bar");if(v.percentile==null){d.append(node("small",statuses[v.status]||"Unavailable"));return d;}const p=node("progress");p.max=100;p.value=v.percentile;p.setAttribute("aria-label","Percentile "+number(v.percentile));d.append(p,node("span",number(v.percentile)));return d;}
function metricDetails(profile){return Object.entries(profile.metrics).map(([m,v])=>[label(m),number(v.value)+(v.value==null?"":v.unit==="per90"?" /90":""),percentile(v),v.peer_count||"—",v.coverage==null?"No opportunities":number(v.coverage*100)+"%"]);}
async function explore(){const serial=++requestSerial;const parent=clear("profile");if(!$("player").value){message(parent,"No players match this filter.","empty");return;}message(parent,"Loading player profile…");try{const p=await api("/api/profile?"+query(ref($("player").value)));if(serial!==requestSerial)return;parent.replaceChildren();const identity=card(),heading=node("div",null,"identity"),left=node("div");left.append(node("h2",p.player_name),node("p",p.team_name,"subtle"));heading.append(left,node("span",p.peer_eligible?"Peer eligible":"Limited comparison coverage","badge"+(p.peer_eligible?"":" warn")));identity.append(heading);const stats=node("div",null,"stats");for(const [name,value] of [["Validated minutes",number(p.denominator_minutes)],["Primary position",p.primary_position_group||"Mixed usage"],["Dominant share",number(p.dominant_position_share*100)+"%"],["Appearances",p.appearances]]){const n=node("div",null,"stat");n.append(node("strong",value),node("span",name));stats.append(n);}identity.append(stats);if(p.partial_player_season)identity.append(node("p","Partial player season: quarantined appearances are excluded.","unavailable"));for(const reason of p.eligibility_reasons)identity.append(node("span",label(reason.toLowerCase()),"badge warn"));parent.append(identity);const categories=card("Relative activity profiles");categories.append(node("p","Equal-weight category summaries; no overall player rating.","note"));for(const [name,v] of Object.entries(p.categories)){const row=node("div",null,"category");row.append(node("span",label(name)));if(v.score!=null){const bar=node("progress");bar.max=100;bar.value=v.score;bar.setAttribute("aria-label",label(name)+" score "+number(v.score));row.append(bar,node("strong",number(v.score)));row.append(node("small",`${v.peer_count} complete peers · ${v.metrics.map(label).join(", ")}`));}else row.append(node("small",statuses[v.status]||"Unavailable"));categories.append(row);}parent.append(categories);const metrics=card("Metrics and peer percentiles");metrics.append(node("p","Counts and sums use per 90. Means and percentages use their raw value. Each metric exposes its own complete peer count and source coverage.","note"),table(["Metric","Value","Percentile","Complete peers","Coverage"],metricDetails(p)));parent.append(metrics);}catch(e){if(serial===requestSerial){parent.replaceChildren();message(parent,e.message,"message error");}}}
function filterPlayers(){const q=$("search").value.toLocaleLowerCase(),role=$("role").value;selectFill("player",players.filter(p=>(!role||p.primary_position_group===role)&&(p.player_name+" "+p.team_name).toLocaleLowerCase().includes(q)));explore();}
$("search").addEventListener("input",filterPlayers);$("role").addEventListener("change",filterPlayers);$("player").addEventListener("change",explore);
$("compare-run").addEventListener("click",()=>action($("compare-run"),"comparison",async parent=>{const refs=[$("compare-a").value,$("compare-b").value,$("compare-c").value].filter(Boolean).map(ref);const result=await api("/api/compare",{players:refs});parent.replaceChildren();for(const w of result.warnings)message(parent,w);const header=["Metric",...result.profiles.map(p=>`${p.player_name} · ${p.primary_position_group||"mixed"} · ${number(p.denominator_minutes)} min`)];const rows=Object.keys(result.profiles[0].metrics).map(m=>[label(m),...result.profiles.map(p=>{const v=p.metrics[m],n=node("div");n.append(node("span",number(v.value)+(v.value!=null&&v.unit==="per90"?" /90":"")),node("small",v.percentile==null?(statuses[v.status]||"Percentile unavailable"):`${number(v.percentile)} percentile · ${v.peer_count} peers`));return n;})]);const c=card("Player comparison");c.append(table(header,rows));parent.append(c);}));
$("similar-run").addEventListener("click",()=>action($("similar-run"),"similarity",async parent=>{const r=await api("/api/similar?"+query({...ref($("similar-player").value),top_k:$("similar-k").value}));parent.replaceChildren();if(r.status!=="AVAILABLE"){message(parent,statuses[r.status]||r.status,"empty");message(parent,`${r.peer_count} complete peers; ${r.minimum_peer_count} required.`);return;}message(parent,`${r.peer_count} complete peers · ${r.active_features.length} active metrics · query player excluded from all team spells.`);const c=card("Similar event profiles");c.append(table(["Player / team","Minutes","Distance","Similarity index","Closest metrics","Largest differences"],r.neighbors.map(n=>[`${n.player_name} · ${n.team_name}`,number(n.denominator_minutes),number(n.distance),number(n.similarity_score),n.key_similarities.map(d=>label(d.metric)).join(", "),n.key_differences.map(d=>`${label(d.metric)} (${number(d.standardized_difference)} standardized)`).join(", ")])));parent.append(c);for(const w of r.warnings)message(parent,label(w.toLowerCase()));for(const n of r.neighbors){const detail=node("details");detail.append(node("summary",n.player_name+": metric differences"),table(["Metric","Query","Neighbor","Standardized difference","Distance share"],n.feature_differences.map(d=>[label(d.metric),number(d.query_value),number(d.peer_value),number(d.standardized_difference),number(d.contribution_share*100)+"%"])));parent.append(detail);}}));
function renderWeights(){const parent=clear("weights");for(const [m,w] of Object.entries(weightMap)){const row=node("div",null,"weight"),l=node("label",label(m)),input=node("input");input.type="number";input.min="0";input.step="0.1";input.value=w;input.setAttribute("aria-label",label(m)+" weight");input.addEventListener("input",()=>weightMap[m]=Number(input.value));l.append(input);const remove=node("button","×");remove.setAttribute("aria-label","Remove "+label(m));remove.addEventListener("click",()=>{delete weightMap[m];renderWeights();});row.append(l,remove);parent.append(row);}}
function metricOptions(){const s=$("add-metric");s.replaceChildren();for(const m of meta.ranking_metrics[$("rank-role").value]||[])s.append(new Option(label(m),m));}
function preset(){const req=meta.requirements[$("preset").value];$("rank-role").value=req.position_group;$("rank-minutes").value=req.minimum_minutes;$("rank-k").value=req.top_k;weightMap={...req.weights};metricOptions();renderWeights();}
$("preset").addEventListener("change",preset);$("rank-role").addEventListener("change",()=>{const allowed=meta.ranking_metrics[$("rank-role").value]||[];weightMap=Object.fromEntries(Object.entries(weightMap).filter(([m])=>allowed.includes(m)));metricOptions();renderWeights();});$("add-weight").addEventListener("click",()=>{if($("add-metric").value){weightMap[$("add-metric").value]=1;renderWeights();}});
$("rank-run").addEventListener("click",()=>action($("rank-run"),"ranking",async parent=>{const r=await api("/api/rank",{name:"Interactive scouting requirement",position_group:$("rank-role").value,minimum_minutes:Number($("rank-minutes").value),top_k:Number($("rank-k").value),weights:weightMap});parent.replaceChildren();message(parent,`${r.peer_count} complete reference players · priorities: ${Object.entries(r.normalized_weights).map(([m,w])=>label(m)+" "+number(w*100)+"%").join(", ")}`);if(r.status!=="AVAILABLE"){message(parent,statuses[r.status]||r.status,"empty");return;}message(parent,"Requirement scores reflect these activity priorities, not overall ability. Candidate filters retain the full reference benchmark.");const c=card("Ranked candidates");c.append(table(["Rank","Player / team","Minutes","Requirement score","Main contributions","Lower requested percentiles"],r.rankings.map(n=>[n.rank,`${n.player_name} · ${n.team_name}`,number(n.denominator_minutes),number(n.recruitment_score),n.ranking_reasons.map(d=>`${label(d.metric)}: ${number(d.percentile)} percentile`).join("; "),n.weaker_dimensions.map(d=>`${label(d.metric)}: ${number(d.percentile)}`).join("; ")])));parent.append(c);for(const n of r.rankings){const d=node("details");d.append(node("summary",n.player_name+": score contributions"),table(["Metric","Value","Direction","Percentile","Weight","Contribution"],Object.entries(n.components).map(([m,v])=>[label(m),number(v.value),v.direction,number(v.percentile),number(v.normalized_weight*100)+"%",number(v.contribution)])));parent.append(d);}const excluded=node("details");excluded.append(node("summary",`${r.exclusions.length} excluded player/team records`),table(["Player / team record","Reason"],r.exclusions.map(e=>{const p=players.find(p=>p.player_id===e.player_id&&p.team_id===e.team_id);return [p?`${p.player_name} · ${p.team_name}`:"Unknown record",e.reasons.map(x=>label(x.toLowerCase())).join(", ")];})));parent.append(excluded);}));
const titles={explore:["Player Explorer","Explore validated minutes, role usage, and peer-relative event profiles."],compare:["Player Comparison","Compare two or three team spells and inspect differences without hiding coverage."],similar:["Similar Players","Find within-position event profiles and inspect what drives their proximity."],rank:["Recruitment Search","Set a scouting requirement and inspect every weighted contribution."]};
for(const b of document.querySelectorAll("nav button"))b.addEventListener("click",()=>{for(const other of document.querySelectorAll("nav button")){other.classList.toggle("active",other===b);if(other===b)other.setAttribute("aria-current","page");else other.removeAttribute("aria-current");}for(const [view,t] of Object.entries(titles))$("panel-"+view).hidden=view!==b.dataset.view;[$("view-title").textContent,$("view-description").textContent]=titles[b.dataset.view];});
async function init(){try{meta=await api("/api/meta");players=(await api("/api/players")).sort((a,b)=>a.player_name.localeCompare(b.player_name)||a.team_name.localeCompare(b.team_name));$("cohort").textContent="WSL · "+meta.season+" · Verified snapshot";const coverage=clear("coverage");coverage.append(node("p",`${meta.unique_players} players · ${meta.profile_count} team spells · ${meta.eligible_profiles} peer eligible`),node("p",`At least ${meta.minimum_minutes} minutes and ${meta.minimum_peers} complete peers for comparisons. Minutes include stoppage time.`));for(const text of meta.limits)coverage.append(node("p",text));coverage.append(node("small","Snapshot "+meta.profile_manifest_sha256.slice(0,12)));for(const role of meta.roles){$("role").append(new Option(role,role));$("rank-role").append(new Option(role,role));}for(const name of Object.keys(meta.requirements))$("preset").append(new Option(meta.requirements[name].name,name));$("rank-minutes").min=meta.minimum_minutes;selectFill("player",players);for(const id of ["compare-a","compare-b","similar-player"])selectFill(id,players);selectFill("compare-c",players,true);const eligible=players.filter(p=>p.peer_eligible&&p.primary_position_group==="CB").sort((a,b)=>b.denominator_minutes-a.denominator_minutes);if(eligible.length){for(const id of ["player","compare-a","similar-player"])$(id).value=key(eligible[0]);if(eligible.length>1)$("compare-b").value=key(eligible[1]);}$("preset").value=Object.keys(meta.requirements).find(n=>meta.requirements[n].position_group==="CB")||Object.keys(meta.requirements)[0];preset();if(!meta.full_cohort)message(coverage,"Partial diagnostic cohort: comparison coverage is restricted.");await explore();}catch(e){$("global-error").hidden=false;$("global-error").textContent="Unable to load verified data: "+e.message;clear("profile");message($("profile"),"No fallback player statistics are generated.","empty");}}
init();
